name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
categories:
  - title: '### Added'
    labels: ['feature', 'enhancement']
  - title: '### Changed'
    labels: ['breaking', 'change']
  - title: '### Fixed'
    labels: ['bug', 'fix']
  - title: '### Security'
    labels: ['security']
  - title: '### Performance'
    labels: ['performance']
  - title: '### Accessibility'
    labels: ['accessibility', 'a11y']
  - title: '### Code Quality'
    labels: ['maintenance', 'chore', 'refactor', 'code-quality']
  - title: '### Documentation'
    labels: ['documentation', 'docs']
template: |
  ## What's Changed
  
  $CHANGES
  
  ## Contributors
  
  $CONTRIBUTORS
  
  **Full Changelog**: $PREVIOUS_TAG...v$RESOLVED_VERSION

